[scenes]
[scenes.1]
name = "CAMERA 1"
color = "#cc241d"

[scenes.2]
name = "CAMERA 2"
color = "#458588"

[scenes.3]
name = "CAMERA 3"
color = "#98971a"

[scenes.4]
name = "CAMERA 4"
color = "#b16286"
